# Generated by Django 3.2.7 on 2021-09-12 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=80)),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['marca', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del cargo')),
                ('nivel', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['nombre', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField()),
                ('fecha_alta', models.DateField(default=datetime.datetime(2021, 9, 12, 19, 53, 53, 798801), verbose_name='Fecha de Alta')),
            ],
            options={
                'ordering': ['categoria', 'persona'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='N° de Documento')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre/s')),
                ('fecha_nac', models.DateField(default=datetime.datetime(2021, 9, 12, 19, 53, 53, 798801), verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=15, verbose_name='N° de Telefono')),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=90)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='tienda.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=70, verbose_name='Tipo de Movimiento')),
                ('numero', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime(2021, 9, 12, 19, 53, 53, 798801))),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_cliente', to='tienda.cliente')),
            ],
            options={
                'ordering': ['tipo', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_articulo', to='tienda.articulo')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_movimiento', to='tienda.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False, verbose_name='N° de Legajo')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_cargo', to='tienda.cargo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_persona', to='tienda.persona')),
            ],
            options={
                'ordering': ['legajo'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empleado', to='tienda.persona'),
        ),
    ]
