# Generated by Django 3.2.7 on 2021-09-22 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20210922_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 15, 57, 17, 178970), verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 15, 57, 17, 178970)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 15, 57, 17, 170967), verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(blank=True, default='Seleccione una opcion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='tienda.localidad'),
        ),
    ]
