# Generated by Django 3.2.7 on 2021-09-22 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20210922_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='disponible',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'No Disponible')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 16, 26, 58, 270766), verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 16, 26, 58, 270766)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 16, 26, 58, 270766), verbose_name='Fecha de Nacimiento'),
        ),
    ]
