# Generated by Django 3.2.7 on 2021-09-22 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20210922_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 16, 42, 27, 605478), verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 16, 42, 27, 605478)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 16, 42, 27, 605478), verbose_name='Fecha de Nacimiento'),
        ),
    ]
