# Generated by Django 3.2.7 on 2021-10-08 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_auto_20211008_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='artuculos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 18, 31, 25, 349206), verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 18, 31, 25, 350204)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 18, 31, 25, 344204), verbose_name='Fecha de Nacimiento'),
        ),
    ]
